services:
  node-server:
    container_name: node
    build: .
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: db
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root # Root user password
      MYSQL_DATABASE: tutorial # Initial database
    ports:
      - "3307:3306" # Change this line to map host port 3307 to container port 3306
    volumes:
      - mysql_data_test:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    platform: linux/amd64 # Use the amd64 platform with emulation
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data_test: # กำหนดชื่อ volume ที่จะใช้สร้างข้อมูล
    driver: local